name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O 'master' según tu rama principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Añadimos esto para obligar a GitHub a usar Node 24 y quitar el warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5 # 👈 Actualizado a v5

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Usamos una versión de Node más moderna para tu proyecto
          cache: 'npm'

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build 🏗️
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages